/**
 * One disclaimer, used by every AI implementation so the wording cannot
 * drift between the live and sample paths.
 */
export const AI_DISCLAIMER =
  'This summary was generated by a language model from the data shown on this page. ' +
  'It is not financial advice, it may contain errors, and it should not be the basis of ' +
  'an investment decision. Verify anything material against the underlying sources.';
